from get_product import get_data


url_dict = {
    ('living','문구','펜/노트'):'https://wiggle-wiggle.com/product/list.html?cate_no=489'
    ,('living','문구','자/마그넷/스테이플러'):'https://wiggle-wiggle.com/product/list.html?cate_no=490'
    ,('living','문구','카드/데코용품'):'https://wiggle-wiggle.com/product/list.html?cate_no=492'
    ,('living','미용/욕실용품','칫솔/살균기/홀더'):'https://wiggle-wiggle.com/product/list.html?cate_no=494'
    ,('living','미용/욕실용품','욕실슬리퍼'):'https://wiggle-wiggle.com/product/list.html?cate_no=495'
    ,('living','미용/욕실용품','타월/세안밴드'):'https://wiggle-wiggle.com/product/list.html?cate_no=497'
    ,('living','미용/욕실용품','네일용품'):'https://wiggle-wiggle.com/product/list.html?cate_no=575'
    ,('living','홈데코','홈슬리퍼'):'https://wiggle-wiggle.com/product/list.html?cate_no=501'
    ,('living','홈데코','쿠션/담요/매트'):'https://wiggle-wiggle.com/product/list.html?cate_no=504'
    ,('living','홈데코','조명/포스터'):'https://wiggle-wiggle.com/product/list.html?cate_no=651'
    ,('living','주방용품','컵/머그'):'https://wiggle-wiggle.com/product/list.html?cate_no=505'
    ,('living','주방용품','텀블러'):'https://wiggle-wiggle.com/product/list.html?cate_no=506'
    ,('living','주방용품','주방소품'):'https://wiggle-wiggle.com/product/list.html?cate_no=583'
    ,('living','파티용품','초/데코용품'):'https://wiggle-wiggle.com/product/list.html?cate_no=508'
    ,('living','파티용품','파티컵'):'https://wiggle-wiggle.com/product/list.html?cate_no=509'
    ,('fashion','의류','로브/랩타월'):'https://wiggle-wiggle.com/product/list.html?cate_no=554'
    ,('fashion','의류','파자마'):'https://wiggle-wiggle.com/product/list.html?cate_no=555'
    ,('fashion','의류','상의'):'https://wiggle-wiggle.com/product/list.html?cate_no=556'
    ,('fashion','의류','하의'):'https://wiggle-wiggle.com/product/list.html?cate_no=557'
    ,('fashion','장갑/목도리','장갑'):'https://wiggle-wiggle.com/product/list.html?cate_no=636'
    ,('fashion','장갑/목도리','목도리'):'https://wiggle-wiggle.com/product/list.html?cate_no=637'
    ,('fashion','신발','-'):'https://wiggle-wiggle.com/product/list.html?cate_no=551'
    ,('fashion','가방','피크닉백'):'https://wiggle-wiggle.com/product/list.html?cate_no=558'
    ,('fashion','가방','쇼퍼백'):'https://wiggle-wiggle.com/product/list.html?cate_no=559'
    ,('fashion','액세서리','실리콘참'):'https://wiggle-wiggle.com/product/list.html?cate_no=560'
    ,('fashion','액세서리','우산'):'https://wiggle-wiggle.com/product/list.html?cate_no=561'
    ,('fashion','액세서리','양말'):'https://wiggle-wiggle.com/product/list.html?cate_no=562'
    ,('fashion','액세서리','키링/배지'):'https://wiggle-wiggle.com/product/list.html?cate_no=625'
    ,('fashion','액세서리','기타용품'):'https://wiggle-wiggle.com/product/list.html?cate_no=563'
    ,('outdoor','차량용품','주차번호판'):'https://wiggle-wiggle.com/product/list.html?cate_no=524'
    ,('outdoor','차량용품','방향제'):'https://wiggle-wiggle.com/product/list.html?cate_no=607'
    ,('outdoor','피크닉','피크닉용품'):'https://wiggle-wiggle.com/product/list.html?cate_no=527'
    ,('outdoor','피크닉','보냉백'):'https://wiggle-wiggle.com/product/list.html?cate_no=528'
    ,('outdoor','캠핑/여행','침구류'):'https://wiggle-wiggle.com/product/list.html?cate_no=537'
    ,('outdoor','캠핑/여행','파우치'):'https://wiggle-wiggle.com/product/list.html?cate_no=538'
    ,('outdoor','캠핑/여행','캠핑용품'):'https://wiggle-wiggle.com/product/list.html?cate_no=599'
    ,('outdoor','스포츠','골프'):'https://wiggle-wiggle.com/product/list.html?cate_no=577'
    ,('outdoor','스포츠','테니스'):'https://wiggle-wiggle.com/product/list.html?cate_no=578'
    ,('digital','모바일','폰케이스'):'https://wiggle-wiggle.com/product/list.html?cate_no=513'
    ,('digital','모바일','그립톡'):'https://wiggle-wiggle.com/product/list.html?cate_no=514'
    ,('digital','PC/노트북/패드','마우스/키보드'):'https://wiggle-wiggle.com/product/list.html?cate_no=516'
    ,('digital','PC/노트북/패드','파우치/가방'):'https://wiggle-wiggle.com/product/list.html?cate_no=517'
    ,('digital','카메라','일회용 카메라'):'https://wiggle-wiggle.com/product/list.html?cate_no=610'
    ,('electronics','-','-'):'https://wiggle-wiggle.com/product/list.html?cate_no=712'
    ,('family','키즈','의류'):'https://wiggle-wiggle.com/product/list.html?cate_no=638'
    ,('family','키즈','잡화'):'https://wiggle-wiggle.com/product/list.html?cate_no=545'
    ,('family','펫','장난감'):'https://wiggle-wiggle.com/product/list.html?cate_no=547'
    ,('family','펫','용품'):'https://wiggle-wiggle.com/product/list.html?cate_no=548'
    ,('collabo','ARENA','여성 수영복'):'https://wiggle-wiggle.com/product/list.html?cate_no=709'
    ,('collabo','ARENA','키즈 수영복'):'https://wiggle-wiggle.com/product/list.html?cate_no=710'
    ,('collabo','ARENA','수모/ACC'):'https://wiggle-wiggle.com/product/list.html?cate_no=711'
    ,('collabo','Bellygom','-'):'https://wiggle-wiggle.com/product/list.html?cate_no=571'
    ,('collabo','Locknlock','-'):'https://wiggle-wiggle.com/product/list.html?cate_no=572'
    ,('collabo','Glasslock','-'):'https://wiggle-wiggle.com/product/list.html?cate_no=573'
    ,('collabo','Ki Eun Se','-'):'https://wiggle-wiggle.com/product/list.html?cate_no=568'
    ,('collabo','Goldenbear','-'):'https://wiggle-wiggle.com/product/list.html?cate_no=570'
    ,('collabo','KAKAOFRIENDS','-'):'https://wiggle-wiggle.com/product/list.html?cate_no=701'
    ,('collabo','ABKO','-'):'https://wiggle-wiggle.com/product/list.html?cate_no=705'
}

for k,v in url_dict.items():
    large_category = k[0]
    middle_category = k[1]
    small_category = k[2]
    url = v
    get_data(large_category,middle_category,small_category,url)
